### PR TITLE
Added long_description_content_type in setup.py.

### PR DESCRIPTION
**Pull request by RatanShreshtha**
To include README in package’s metadata

### CODE REVIEW

**Comment by njsmith** [comment]
Hey, sorry I missed this.

Does including the mime-type here actually do anything? I thought ReST was the default, and it's always seemed to work OK on my other packages...

**Comment by RatanShreshtha** [comment]
Yes, in PYPI doc its mentioned to include the `long_description_content_type` in `setup.py`.

**Comment by altendky** [comment]
I have definitely seen several projects with mis-rendered descriptions on PyPI that also didn't have the content type specified.  But, I never dug into it very deep.  As a reference point, QTrio presently lacks the content type parameter and does have a properly rendered reST description on PyPI.  Maybe historically there were issues but they are fixed now, I don't know.

https://github.com/altendky/qtrio/blob/v0.1.0/setup.py
https://pypi.org/project/qtrio/0.1.0/

But if we dislike warnings...

```
$ venv/bin/twine check dist/trimeter-0.0.0-py3-none-any.whl 
Checking dist/trimeter-0.0.0-py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```

I'll also note, since I ran into it while checking this, that I think we need to add some build system info to `pyproject.toml`, albeit as a separate task.  `pep517.build` was unhappy.

**Comment by pquentin** [comment]
Thanks!

**Pull request merged**
